### ISSUE TITLE
Different sampling time in fdyn() and my_torqueFunction()

### ISSUE THREAD

**Issue by Betancourt20** [petercorke/robotics-toolbox-python#298]
**Describe the bug**
Hello,
I am doing Task space control and when I call
```
tg = p560nf.fdyn(3, q, tau, dt=0.05)
```
where tau is defined as
```
def tau(p560nf, t, q, qd):
    M = p560nf.inertia(q)
    g = p560nf.gravload(q)
    C = p560.coriolis(q, qd)
    J = p560nf.jacob0(q)
    T = p560nf.fkine(q)
    T = np.array(T)
    J_dot = p560nf.jacob_dot(q, qd)
    x_tilde = tr2delta_explicit(Td, T)
    x_tilde = x_tilde.reshape(6,)
    xdot = J@qd
    p = transl(T)

    nu = np.linalg.pinv(J)@(-Kp@x_tilde - Kv@xdot - J_dot@qd)
    u = M@nu + C@qd + g

    t_list.append(t)
    u_list.append(u)
    p_list.append(p)
    return u
```
I realized that when entering in the tau function, the sampling time is not 0.05 and therefore the size of the vectors  ``t``,``u``, ``p``  are not the same as ``tg.t`` and ``tg.q``. I tried to understand what is exactly happening inside the function fdyn but I did not get it why is changing the sampling time when doing  `` tau = torqfun(self, t, q, qd, **targs)``.
Any thoughts ?
Thanks in advance

**Version information**

Did you install from PyPI or GitHub?
If GitHub what commit hash?
GitHub version 2.25.1

**Comment by petercorke** [comment]
This integrates the equations of motion over time.  Your function tau will get called numerous times at each integration time step in order for the RK45 integrator to dp its thing, check out https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.RK45.html for the SciPy algorithm which is doing the work here.  It is not correct to record u, u, p inside this function because it will end up with a lot of "exploratory" evaluations of the torque function.  The values returned by `fdyn` are the proper values that you want.  You can get your `p` values by computing fkine from the returned joint angles: `p560nf.fkine(tg.q).t`
